name: CI

on:
  pull_request:
    types: ["opened"]
    branches: [master]

jobs:

  automated-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run `typecheck`
        run: yarn typecheck

      - name: Run `lint`
        run: yarn lint

      - name: Run `test`
        run: yarn test
        env:
          ICLOUD_USERNAME: ${{secrets.ICLOUD_USERNAME}}
          ICLOUD_APP_SPECIFIC_PASSWORD: ${{secrets.ICLOUD_APP_SPECIFIC_PASSWORD}}
